version: '3.8'

services:
  devops-angular-frontend:
    build:
      context: https://github.com/ShoroukNabil/DevOps_MVN_Client.git#demo-docker
    container_name: devops-angular-frontend-container
    depends_on:
      - devops-springboot-backend
    networks:
      - devops-network
    ports:
      - "4200:80"
  devops-springboot-backend:
    build: .
    container_name: devops-springboot-backend-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://devops-mysql-database:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Dev_P@ssw0rd
      - SERVER_PORT=8040
    depends_on:
      devops-mysql-database:
        condition: service_healthy
    networks:
      - devops-network
    ports:
      - "8040:8040"
    restart: on-failure
  devops-mysql-database:
    image: mysql:8.0
    container_name: devops-mysql-database-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dev_P@ssw0rd
      MYSQL_DATABASE: devops
    networks:
      - devops-network
    volumes:
      - devops_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  devops-network:
    driver: bridge

volumes:
  devops_mysql_data:
