version: '3.8'

services:
  app:
    build:
      context: .
    container_name: spring-microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Dev_P@ssw0rd
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dev_P@ssw0rd
      MYSQL_DATABASE: devops
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
