version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dev_P@ssw0rd
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Dev_P@ssw0rd
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: Dev_P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
